import { Gender } from "@prisma/client";
import { Account } from "./Account";
import { Address } from "./Address";
import { City } from "./City";
import { Country } from "./Country";
import { Language } from "./Language";
import { Role } from "./Role";
import { SystemService } from "./SystemService";

export type User = {
  id: string;
  username: string;
  password?: string | null;
  email?: string;
  firstName?: string;
  lastName?: string;
  officialName?: string;
  phone?: string;
  country?: Country;
  city?: City;
  nationality?: Country;
  address?: Address;
  dob?: string;
  phoneLabel?: string;
  emailLabel?: string;
  createdAt?: string;
  accounts: Account[];
  prefix?: string;
  middleName?: string;
  language?: Language;
  gender?: Gender;
  avatar?: string;
  accessToken?: string;
  status?: "approved" | "not-approved" | "blocked";
  userProfileFullFIlled?: boolean;
  addressFullFilled?: boolean;
  mobileFullFilled?: boolean;
  documentsFullFilled?: boolean;
  emailFullFilled?: boolean;
  passwordFullFilled?: boolean;
};
