export type User = {
  id: string;
  username: string;
  password?: string | null;
  email?: string;
  firstName?: string;
  lastName?: string;
  officialName?: string;
  phone?: string;
  country?: string;
  city?: string;
  nationality?: string;
  address?: string;
  dob?: string;
  phoneLabel?: string;
  emailLabel?: string;
  createdAt?: string;
  prefix?: string;
  middleName?: string;
  language?: string;
  gender?: string;
  avatar?: string;
  accessToken?: string;
  status?: "approved" | "not-approved" | "blocked";
  userProfileFullFIlled?: boolean;
  addressFullFilled?: boolean;
  mobileFullFilled?: boolean;
  documentsFullFilled?: boolean;
  emailFullFilled?: boolean;
  passwordFullFilled?: boolean;
};
